<?php

namespace AppBundle\Repository;

use AdminBundle\Repository\BaseRepository;

/**
 * KingsRideRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KingsRideRepository extends BaseRepository
{
}
