<?php

namespace AppBundle\Repository;

/**
 * KingsRideRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KingsRideRepository extends \Doctrine\ORM\EntityRepository
{
}
