<?php

namespace AppBundle\Repository;

/**
 * KingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KingRepository extends \Doctrine\ORM\EntityRepository
{
}
