app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    defaults: { year: 2020 }

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix: admin

logout:
    path: /admin/logout
