security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
    providers:
        our_db_provider:
            entity:
                class: AdminBundle:User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: ~
            form_login:
                default_target_path: /
                login_path: login
                check_path: login
            logout:
                path: /admin/logout
                target: /

    access_control:
        - { path: ^/admin/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }

    role_hierarchy:
        ROLE_SUPER_ADMIN: [ROLE_ADMIN]
